// Vineyard roster, hand-extracted from the Current folder in Drive.
// Static reference data: update this array when Max confirms changes,
// it's not read live from the spreadsheets.
const VINEYARDS = [
  {
    name: "Placitas",
    varieties: "Pinot Noir (clones 777, 115)",
    vines: 801,
    rootstock: "101-14",
    spacing: "8' x 3.3'",
    note: "",
    url: "https://drive.google.com/file/d/131h9XCNH6gBm8Poin6I9ybz7ynE88Dto/view?usp=drivesdk",
  },
  {
    name: "Pierce",
    varieties: "Riesling (clone 12)",
    vines: 132,
    rootstock: "101-14",
    spacing: "5' x 7'-10\"",
    note: "Planted 2007",
    url: "https://docs.google.com/spreadsheets/d/1bgdODOuM7xnwsSqCl1TsBwVgS3PRmn0OOybKIp7rwW0/edit",
  },
  {
    name: "Dehlinger",
    varieties: "Merlot (clone 181)",
    vines: 297,
    rootstock: "101-14",
    spacing: "6' x 8'",
    note: "Planted 2003",
    url: "https://drive.google.com/file/d/1eIzC5oJVuKHDWveTzIN_J0nvKIun7bDf/view?usp=drivesdk",
  },
  {
    name: "Old Church Rd",
    varieties: "Chardonnay, Riesling, Merlot, Zinfandel, Roussanne",
    vines: 2600,
    rootstock: "mostly 101-14",
    spacing: "",
    note: "2.49 acres total",
    url: "https://drive.google.com/file/d/1Yu9xJvlhtiUe05_NArgw1ROZg565rTwD/view?usp=drivesdk",
  },
  {
    name: "Lynn",
    varieties: "Pinot Noir (clone 115) + Gruner Veltliner (clone 03), two blocks",
    vines: 860,
    rootstock: "101-14",
    spacing: "8'x3.3' (PN), 7.5'x5' (GV)",
    note: "510 Pinot Noir + 350 Gruner Veltliner",
    url: "https://drive.google.com/file/d/1zU-xJJwnxilG4LYpVNWBgF6LqNF4gHM1/view?usp=drivesdk",
  },
  {
    name: "Farm Stand",
    varieties: "Roussanne (clone 468)",
    vines: 292,
    rootstock: "101-14",
    spacing: "7-8' x 5'",
    note: "",
    url: "https://drive.google.com/file/d/1mx4knRRq4-hXmiPhr5PfI03QjIrB_wpX/view?usp=drivesdk",
  },
  {
    name: "Gerhart",
    varieties: "Riesling (own rooted) + Semillon",
    vines: 833,
    rootstock: "101-14 (Semillon)",
    spacing: "8' x 5'",
    note: "0.765 acres",
    url: "https://drive.google.com/file/d/1AA8bkQxo3IWAZV_JVCOvFlcep0cU743-/view?usp=drivesdk",
  },
  {
    name: "Corrales Road",
    varieties: "Chardonnay, Zinfandel, Merlot, Mourvèdre, Cabernet Sauvignon, Semillon",
    vines: null,
    rootstock: "mostly 101-14",
    spacing: "mixed, 8'x6' in newer zone",
    note: "1,200+ vines across multiple zones, exact total not consolidated in source",
    url: "https://drive.google.com/file/d/1hEFJXdUGvuE8L8kb2HZ1SEzx0ODLnADu/view?usp=drivesdk",
  },
  {
    name: "Franklin",
    varieties: "Cabernet Sauvignon, Riesling, Semillon, Cab Franc, Petite Sirah, Merlot, Chardonnay, Pinot Noir, Zinfandel, Sauvignon Blanc, Gewürztraminer",
    vines: 1254,
    rootstock: "mixed",
    spacing: "mixed, 5.25' to 7' rows",
    note: "",
    url: "https://drive.google.com/file/d/1V945XkzJvk-xDQSbv8S9xPRvGyhnts46/view?usp=drivesdk",
  },
  {
    name: "Mirasol",
    varieties: "Mourvèdre (clone 369) + Gruner Veltliner (clone 01)",
    vines: 578,
    rootstock: "101-14",
    spacing: "7.5' x 5'",
    note: "356 Mourvèdre + 222 Gruner Veltliner, planted 2024 to 2025",
    url: "https://drive.google.com/file/d/1K0LGsx_FzY8EXkqloEupgKsAc0AFObHY/view?usp=drivesdk",
  },
  {
    name: "Coronado",
    varieties: "Cabernet Franc + Cabernet Sauvignon, two blocks",
    vines: 1335,
    rootstock: "101-14",
    spacing: "7.5' x 5'",
    note: "728 vines planted 2011 (west) + 607 planted 2021 (east)",
    url: "https://drive.google.com/file/d/1Mu_Sin12BH18YShZH44WVPOSJwFiKPey/view?usp=drivesdk",
  },
  {
    name: "Williams",
    varieties: "Roussanne (clone 468) + Riesling (clone 12)",
    vines: 237,
    rootstock: "101-14",
    spacing: "8' x 5'",
    note: "~0.22 acres combined",
    url: "https://drive.google.com/file/d/1ZvYaq_2FRR9Iqqq4Ydx70y8HPX97jVo1/view?usp=drivesdk",
  },
  {
    name: "Waszak",
    varieties: "Chardonnay + Cabernet Sauvignon",
    vines: 114,
    rootstock: "",
    spacing: "5' x 5'",
    note: "0.065 acres",
    url: "https://drive.google.com/file/d/11n7gnZ-u4o55crfSTgrN_eVCEp0S9i6A/view?usp=drivesdk",
  },
  {
    name: "Saiz",
    varieties: "Gewürztraminer",
    vines: 147,
    rootstock: "",
    spacing: "7' x 5'",
    note: "0.094 acres",
    url: "https://drive.google.com/file/d/1jl88wj2VFWWVX0pxvEkcn7LjOiNiI133/view?usp=drivesdk",
  },
  {
    name: "Fletcher",
    varieties: "Zinfandel (Dupratt clone) + Riesling (clone 12)",
    vines: 440,
    rootstock: "101-14",
    spacing: "8' x 5'",
    note: "",
    url: "https://drive.google.com/file/d/1ySC_muDh7NEsNudcg8q6XRA6qyL4ENP0/view?usp=drivesdk",
  },
  {
    name: "Voorhees",
    varieties: "Chardonnay, Sauvignon Blanc, Merlot (clone 181)",
    vines: 272,
    rootstock: "101-14",
    spacing: "mixed, 6x8 to 10x6",
    note: "Reflects the 2014 replant snapshot (44 Chardonnay, 20 Sauvignon Blanc, 208 Merlot), not a full current count",
    url: "https://drive.google.com/file/d/1kfJy0Ouw18c28NkmLcU1LGTqWM78BOWj/view?usp=drivesdk",
  },
  {
    name: "Mason (Klos-Dillon)",
    varieties: "Syrah",
    vines: 258,
    rootstock: "",
    spacing: "",
    note: "",
    url: "https://drive.google.com/file/d/1THOb_jh_YDXjcZC4cxVhwOQFOG952QEI/view?usp=drivesdk",
  },
  {
    name: "Wilkinson",
    varieties: "Syrah (clone 471)",
    vines: 292,
    rootstock: "101-14",
    spacing: "",
    note: "",
    url: "https://drive.google.com/file/d/13pw-Z2Gg5kB6gFdEvdNEh1F_K1IU8K4f/view?usp=drivesdk",
  },
  {
    name: "Fontana",
    varieties: "Gruner Veltliner",
    vines: 95,
    rootstock: "",
    spacing: "8' x 5'",
    note: "Planted ~2020",
    url: "https://drive.google.com/file/d/1K_ZFFTLTR8m0TSYuifGRjV0o0oOOjS4r/view?usp=drivesdk",
  },
  {
    name: "Cowen",
    varieties: "Viognier, Zinfandel",
    vines: null,
    rootstock: "",
    spacing: "8' rows x 5' vines",
    note: "No planting layout on file, soil and nutrient reference only",
    url: "https://drive.google.com/file/d/1t5GVswWDEZ_n3di2WSqAT2tE9t61qPXB/view?usp=drivesdk",
  },
];
